apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-lab.fullname" . }}-nginx
  labels:
    {{- include "platform-lab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "platform-lab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "platform-lab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "platform-lab.fullname" . }}-config
            - secretRef:
                name: {{ include "platform-lab.fullname" . }}-secret
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
