apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-lab.fullname" . }}-secret
  labels:
    {{- include "platform-lab.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secret.redisPassword }}
  API_KEY: {{ .Values.secret.apiKey }}
