name: CI

on:
  push:
    branches: [dev]
    paths-ignore:
      - "platform-lab/values.yaml"

permissions:
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/platform-engineering-lab:$IMAGE_TAG ./app
          docker push $ECR_REGISTRY/platform-engineering-lab:$IMAGE_TAG

      - name: Update values.yaml
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}

        run: |
          wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /usr/local/bin/yq
          yq e '.nginx.image.repository = "'$ECR_REGISTRY'/platform-engineering-lab"' \
            -i platform-lab/values.yaml
          yq e '.nginx.image.tag = "'$IMAGE_TAG'"' \
            -i platform-lab/values.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add platform-lab/values.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push
